config/routes.rb
Rails.application.routes.draw do

   root 'home#index'

   get 'auth/twitter/callback', to: 'sessions#create'

   get '/logout', to: 'sessions#destroy'

    get 'map' => 'map#index'

  resources :map do
      collection do
        post :index
      end
  end

   post 'map/' => 'map#index'

end

app/models/user.rb
class User < ActiveRecord::Base

  def self.find_or_create_from_auth_hash(auth_hash)
    user = where(username: auth_hash[:info][:nickname]).first_or_create
    #raise :test
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(username: session[:user_name]) if session[:user_name]

  end
  helper_method :current_user

  def login_required
    redirect_to('/') if (session[:user_name] == nil)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    
  end

end

app/controllers/map_controller.rb
require 'classes/google_api'
require 'classes/twitter_api'

class MapController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter do
    if (session[:user_name] == nil)
      redirect_to('/')
    end
  end

  # protect_from_forgery with: :exceptionrake routes
    def index
      if params.has_key?(:q)
        handle_input
      else if params.has_key?(:lat)
        handle_map_click
      else
        twitter_helper = TwitterApi.new
        @tweet_list = twitter_helper.query_by_username(session[:user_name]).to_json
      end
    end

  end
  def handle_input
    if(params.has_key?(:t))
      time = params[:t]
      time.gsub!("/", "-")
    else
      time = Time.now.strftime("%d-%m-%Y")
    end
    twitter_helper = TwitterApi.new
    if params[:q].start_with?( '@' )
      @tweet_list = twitter_helper.query_by_username(params[:q]).to_json
    else
      # @tweet_list.to_json
      google_helper = GoogleAPI.new
      coord = google_helper.find_coordinates(params[:q])
      @tweet_list = twitter_helper.query_by_location(coord, 5, time).to_json
    end

  end

  def handle_map_click
    if(params.has_key?(:t))
      time = params[:t]
      time.gsub!("/", "-")
    else
      time = Time.now.strftime("%d-%m-%Y")
    end
    coord_for_click = Coordinate.new(params[:lat],params[:lng])
    twitter_helper_for_click = TwitterApi.new
    @tweet_list = twitter_helper_for_click.query_by_location(coord_for_click, 5, time).to_json
    render :json => {
               :file_content => @tweet_list
           }
    a = 1
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_or_create_from_auth_hash(auth_hash)
    session[:user_name] = @user.username

    redirect_to root_path
  end

  def destroy

    session[:user_name] = nil
    redirect_to root_path
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goole_map_helper.rb
module GooleMapHelper
end

app/helpers/map_query_helper.rb
module MapQueryHelper
end

app/helpers/search_queries_helper.rb
module SearchQueriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/index.erb
<h1> Home</h1>

<a href = "/auth/twitter">Sign in!</a>
<a href = "/logout">Log Out</a>
<a href = "/map">map</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TweetMaps</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'default', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class=navbar-header">
      <a class="navbar-brand" href="#">
        TweetMap
      </a>
      <% if current_user %>
        <p class="navbar-text navbar-right">Signed in as <%=current_user.username %></p>
      <% end %>
    </div>
  </div>
</nav>

<%= yield %>

</body>
</html>

app/views/map/_datepicker.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script>
      $(function() {
          $( ".date" ).datepicker();
      });
  </script>
</head>
<body>

</body>
</html>

app/views/map/_map.js.erb
$(document).ready(function () {

    $('#tweet-button').click(function (event) {
        $(".tweetbox").toggle();
    });

});

app/views/map/_tweetbox.erb
<div class="tweetbox">
Tweet box
</div>

app/views/map/index.html.erb
<!DOCTYPE html>
<html>

<head>
  <style type="text/css">
      html, body, #map-canvas { height: 100%; margin: 0; padding: 0;}
      #tweetTable{
          border: 1px solid;
          margin-left: auto;
          margin-right: auto;
      }
      td, tr{
          border: 1px solid;
      }
  </style>

  <script type="text/javascript"
          src="https://maps.googleapis.com/maps/api/js?key=AIzaSyArzyYKcUontlx0HrhLxTFL5n6975qE_nw">
  </script>
  <script>
        var map;
        var marker;
        var markers = [];
      function initialize() {
         var mapOptions = {
              center: { lat: 49.607, lng: 6.1329},
              zoom: 8
         };
         map = new google.maps.Map(document.getElementById('map-canvas'),mapOptions);

         google.maps.event.addListener(map, 'dblclick', function(e) {
            alert(e.latLng.lat() +" "+ e.latLng.lng());
            //ajax callback
            function ajaxCallback(){
                return jQuery.ajax({
                    data: {lat: e.latLng.lat(), lng: + e.latLng.lng()},
                    dataType: 'script',
                    type: 'post',
                    url: "/map"
                });
            }
            var promise = ajaxCallback();
            promise.success(function () {
                initialize();
            });
            promise.error(function () {
                 alert("nope");
             });
         });
         createMarker();
      }

      google.maps.event.addDomListener(window, 'load', initialize);

      function displayTable(tableData){
          var result = "<table id='tweetTable'>";
          result+="<tr style='font-weight:bold'>"
                  + "<td>User Name</td>"
                  + "<td>Tweet Text</td>"
                  + "</tr>";

          for(var i=0; i<tableData.length; i++) {
              result += "<tr>";

                  result += "<td>"+tableData[i].user.name+"</td>";
                  result += "<td>"+tableData[i].text+"</td>";

              result += "</tr>";
          }
          result += "</table>";

          document.getElementById("table").innerHTML = result;
      }

      function createMarker(){
//          var array = JSON.parse(<%= raw @tweet_list %>);
//          var test = document.getElementById('tweets_info').innerHTML;
          var tweetsJson = document.getElementById('tweets_info').innerHTML;
          var tweetArray = JSON.parse(tweetsJson);
          displayTable(tweetArray);
          for(var i = 0; i < tweetArray.length; i++){
              marker = new google.maps.Marker({
                  position: { lat: tweetArray[i].coordinates.latitude, lng: tweetArray[i].coordinates.longitude },
                  map: map,
                  title: tweetArray[i].text,
                  clickable: true
              });
              markers.push(marker);
          }

          for(var i = 0; i < markers.length; i++){
              google.maps.event.addListener(markers[i], 'click', function() {
                  window.alert(this.title);
              });
          }

          if(marker){
              map.setZoom(6);
              map.panTo(marker.position);
          }
      }
  </script>

</head>

    <body>
    <div id='tweets_info' style="display: none"><%= raw @tweet_list%></div>
    <div style="margin-bottom: 5%;"></div>
    <%= form_tag map_path do %>
        <%= label_tag(:q, "Enter a location or a username:") %>
        <%= text_field_tag(:q) %>
        <%= render partial: "datepicker"%>
        <%= label_tag(:t, "Date:") %>
        <%= text_field_tag 't', nil, class:'date' %>
        <%= submit_tag("GO!") %>
        <a href = '/logout'> Logout</a>
        <a href = '/map'>Display Tweets</a>
        <%= session[:user_name] %>
    <% end %>


    <div style="margin-bottom: 5%;"></div>
    <div id="wrapper" style="height: 40em; width: 80%; margin-left: 10%;">
        <div id="map-canvas"></div>
    </div>
    <div id="table" style="margin-top: 5%; text-align: center; margin-bottom: 5%;">

    </div>
</body>
</html>

app/views/twitter_api/index.html.erb
<h1>hi</h1>